### ISSUE TITLE
Error Pulling Data

### ISSUE THREAD

**Issue by ksauln** [JoGall/FantasyPL#1]
First off this is great and what I've been looking for, I have been searching for anything to scrape the data R or Python. I am not the most advanced coder but I know a little bit.

When creating the player_bygw data frame I am getting an error saying: 

Error in df[, c(7, 2, 54, 6, 4, 5, 9:13, 8, 16:51)] : 
  incorrect number of dimensions 

I looked at the
df <- fromJSON("https://fantasy.premierleague.com/drf/element-summary/5")$history  
to just see one instance in the loop and saw that it was a an empty list. Is this because no games have been played this season?

**Comment by JoGall** [comment]
Yeah it's because there's no data yet. If you look at the [JSON code for any player](https://fantasy.premierleague.com/drf/element-summary/5) the 'history' tag is empty (`"history":[]`), leading to an empty list being imported to R.

I'll have to wait until the season starts to see if the code still works as they may change the format of the data in the API. If you're looking for data to work with for now though, you can find all of last season's data in the file `16-17_raw.csv`.

**Comment by ksauln** [comment]
Gotcha makes sense. I think until the season starts I'll use your excel file and try and play around with the history_past since it looks like it has the overall stats from the previous years they were in the league

**Comment by JoGall** [comment]
Yeah `history_past` has previous season summaries but it would be useful to have week-by-week data from previous seasons too for building prediction models. Hopefully someone somewhere has scraped the APIs for previous seasons but I'm still on the lookout for them...

Let me know if you do anything interesting with the data!
